In [5]:
import numpy as np

### Activation Functions

In [12]:
class Sigmoid:
    def __init__(self):
        self.out = None
        
    def forward(self, x):
        self.out = 1 / (1 + np.exp(-x))
        return self.out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx

### Cost function

In [24]:
class Softmax:
    def __init__(self):
        self.params = []
    
    def forward(self, x):
        e_x = np.exp(x - np.max(x))
        return e_x / e_x.sum()

### Simple Network

In [19]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None
        
    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + b
        self.x = x
        return out
    
    def backward(self, dout):
        W, b = self.params
        dx = np.matmul(dout, W.T)
        dW = np.matmul(self.x.T, dout)
        db = np.matmul(dout, axis = 0)
        
        self.grads[0][...] = dW
        self.grads[1][...] = db
        return dx

### Two Layer Network

In [20]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        
        self.params = []
        for layer in self.layers:
            self.params+= layer.params
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [22]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(s)

[[-2.8855893  -1.10423087 -1.03761523]
 [-1.94203043 -1.16000747 -1.82122261]
 [-2.38937482 -1.16600255 -1.4589397 ]
 [-2.34148404 -0.76493487 -1.4233485 ]
 [-3.26802014 -1.32275103 -0.7712124 ]
 [-1.43525104 -0.66377806 -2.10096673]
 [-2.05079619 -0.69746658 -1.70303481]
 [-2.67697755 -1.31645519 -1.25535988]
 [-1.99321588 -0.83348543 -1.70416543]
 [-3.27708605 -1.18653116 -0.74348961]]


## CNN